### ISSUE TITLE
@eclipse-glsp/protocol depends on potentially incompatible version of vscode-jsonrpc

### ISSUE THREAD

**Issue by dmm9** [eclipse-glsp/glsp#1182]
The symptoms:
The frontend reports an error on initialization. The GLSP client does not initialize correctly and the glsp app does not work.
```
Failed to initialize XXX glsp server with: Uncaught (in promise) Error: Unknown parameter structure auto
```
The first part being glsp/protocol error text, and the last part being vscode-jsonrpc error text.

Why this happens:
* `@eclipse-glsp/protocol 2.0.0` imports `vscode-jsonrpc: "^8.0.2"` -> For me, resolved to **`8.2.0`**
* `@theia/core 1.40.1` imports `vscode-languageserver-protocol: "^3.17.2"` -> For me, resolved to `3.17.3`
  *  `vscode-languageserver-protocol 3.17.3` imports `vscode-jsonrpc: "8.1.0"` -> Resolves to **`8.1.0`**

I didn't dig very deep into this error, but a hint why this happens might be in [this link](https://github.com/TypeFox/monaco-languageclient/issues/254), where it states:
> the culprit is that ParameterStructures is meant to be a singleton [...] having two packaged instances meant there were two instances

This has led me to search in yarn.lock how many instances of vscode-jsonrpc I had. And I had 2.

At the same time, [vscode-jsonrpc's README](https://github.com/Microsoft/vscode-languageserver-node/README.md) states that **version 8.2.0 is a breaking change**. 

A workaround is to add in top-level `package.json` a new `resolutions` entry for `vscode-json`. I can confirm this is what solved the issue for me. But this is specific to each implementation.

As of now, after removing yarn.lock, yarn resolves vscode-languageserver-protocol to version 3.17.5, which already depends on vscode-jsonrpc 8.2.0. So the issue is not visible but it is **still latent** for future versions.

A workaround is to add in top-level `package.json` a new `resolutions` entry for `vscode-json`. I can confirm this is what solved the issue for me. But this is specific to each implementation.

A possible solution would be to make `@eclipse-glsp/protocol` always depend on a fixed version of `vscode-jsonrpc` AND `@theia/core` depend on a fixed version of `vscode-languageserver-protocol`

**Comment by tortmayr** [comment]
Thanks for reporting and digging into this.

In general, we recommend to always upgrade your yarn lock file when updating to a new Theia version. Either by executing `yarn upgrade` or brute-forcing by removing the lock file altogether. Otherwise you might end up with multiple different versions of other packages at well. While in most cases this not a direct issue it is still not ideal to consume different versions of the same package when there is no need.
I guess this is also the reason why we didn't encounter this issue previously.

For now I don't think that there is anything to directly fix this right away, however, we can document this is a known problem in the Theia integration README and mention that it should be fixed by updating outdated lock files.
Nevertheless we have to find a long-term solution as we might run into this issue again once a new version of `vscode-jsonrpc` is released.

>A possible solution would be to make @eclipse-glsp/protocol always depend on a fixed version of vscode-jsonrpc AND @theia/core depend on a fixed version of vscode-languageserver-protocol

That could work. From GLSP's side there is not requirement for a fluent (i.e.^) version. Pinning this to a fixed version would be fine for us. We would have to check with the Theia project whether they have a strict requirement for a fluent version or if it would be fine to pin it. At the very least we should track new release of `vscode-jsonrpc`/`vscode-language-server-protocol` and bump the minimal minor version in Theia to ensure that it can only resolve to one version of `vscode-json-rpc`.
