### ISSUE TITLE
Discussion: Provide a default shape mapping on the client for standard node types

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-glsp/glsp#180]
We could get rid of mapping nodes on the client to default shapes for simple cases if we would provide default types on the server already, such as node:rectangle or node:circle. On the client, we provide a corresponding module that maps the list of default shapes to client nodes, e.g. configureModelElement(context, 'node:rectangle', RectangleNode, RectangleNodeView).

**Comment by planger** [comment]
Sure why not!

I think it would make sense to have a reusable function to register all of the base shapes (such as rectangle, circle, diamond, label, compartment, edge, graph, routing point, etc. to their default data type and view). In a project we also added a rounded rectangle shape, which we could add to the library.

I'd rather call them "base shapes" though instead of default shapes, because in most likely all of the a little more complex diagram implementations you'll often need to add your own node/edge types on top of the base types eventually. Therefore, I think this is mainly to help getting started, but we shouldn't try to hide this view registration, as it is a very common thing to do on typical client implementations (in fact it is often the only thing to be done in the client).

In the beginning of GLSP, we were discussing also the option to position the rendering more on the server too, but we came to the conclusion to abandon that idea, because it would mean to create an abstraction layer over view definition for rendering on the server that would then have to be implemented generically with a specific rendering technology on the client. But this adds a sort-of unnecessary abstraction over a powerful client-side rendering technology (SVG in most cases) that is rather easy to use directly; thus adding indirection, complexity and work while mitigating the power of client rendering technologies (through the server-side abstraction).
So imho it makes sense to keep responsibility for rendering on the client, as the rendering definition is always very closely tied to the UI technology that is used for rendering on the client, and only keep the responsibility to define/create/manipulate the abstract graph model (GModel) on the server -- which then the client needs to render in whatever technology and the necessary configurations that this technology requires.
