### ISSUE TITLE
Implement support for element navigation

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#204]
Similar to how its done in the Theia integration:
![sample](https://user-images.githubusercontent.com/2311075/112281529-6e5c9680-8c86-11eb-8bc4-d109da417046.gif)

**Comment by planger** [comment]
@lforst is looking into this issue! :+1:

**Comment by planger** [comment]
This may involve general VSCode command support, menu items, etc. @lforst will keep us up to date here. Thanks!

**Comment by lforst** [comment]
Hi,

So I was looking into this for quite a while now and while I got the *very* basic functionality to work I ran into a two problems:

 1. I didn't manage to implement the navigation to the documentation. I tried to implement this similarly to how it is done [here in the Theia implementation](https://github.com/eclipse-glsp/glsp-theia-integration/blob/3d0a033d6227868fee49076063260606fe6d11e0/examples/workflow-theia/src/browser/diagram/workflow-navigation-context-menu.ts#L45), but it didn't work. I am now guessing it has to do with a mismatch between the navigate action and the implementation of the example GLSP server.
I would be very grateful for any ideas or pointers on what the issue might be.<br><br>
 2. This one is much more important in my opinion: As far as I understand, VS Code does not support right click context menus in custom editors and web views. I tried this by implementing a web view and a custom editor, both without sprotty, in case sprotty somehow swallows the right click handler, but the context menu seems to be disabled by VS Code itself.
I believe this is not a problem in the Theia integration because the Theia core exposes an API to programmatically render a context menu. VS Code sadly doesn't have such functionality.<br>
**I propose the following solution**: We could create a custom non-native implementation for a context menu in the web view. This feature would only exist in the VS Code implementation and could (hopefully) be exchanged for a native solution as soon as context menus for custom editors ever get added (I already submitted a [feature request](https://github.com/microsoft/vscode/issues/121581)). The custom context menu could bind to the sprotty context menu implementation from this issue: https://github.com/eclipse/sprotty/issues/139
I believe however, that this solution has the precondition of implementing some sort of interface for context menus in the sprotty-vscode integration. I am aware that implementing something like a context menu ourselves is not very optimal and probably somewhat error-prone, but I would still be very interested in hearing your thoughts on this. :)
I might also be completely overthinking this so feel free to tell me if I am missing something completely obvious.

You can find everything I did on this issue so far (which is not a lot) in this draft PR: https://github.com/eclipse-glsp/glsp-vscode-integration/pull/3
It currently just implements the commands for the navigation (without validating whether only one node was selected).

For the meanwhile I would be looking into some other issues but will be happy to pick this one up again after we have declared some next steps.

**Comment by tortmayr** [comment]
Hi,
Regarding 1: I had a quick look and the navigation to the documentation is not working because you need to define a vscode specific action handler that can manage the navigation to an external target. The Theia specific variant is implemented here: https://github.com/eclipse-glsp/glsp-theia-integration/blob/master/packages/theia-integration/src/browser/theia-navigate-to-external-target-handler.ts. Other than that your implementation looks fine

Regarding 2: That is indeed a blocking issue and it looks like the non-native context menu implementation is the way to go here. The context menu is a critical part of GLSP editing and we definitely need a solution here. However, lets wait a bit until you receive a response for your feature request and then let's decide how to proceed with this.

**Comment by tortmayr** [comment]
Closing this. A follow-up issue for the missing context-menu has been created.
