### ISSUE TITLE
Navigation from marker to affected element is no longer working

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#435]
Double clicking on a problem marker does open the corresponding diagram but does not jump to the affected element.
After quickly investigating it it seems like the `ModelInitializationConstraint`of the action dispatcher never completes and the marker navigation functionality depends on this constraint.

**Comment by ivy-lli** [comment]
Hi @tortmayr 

I currently run into the same problem and yes the `ModelInitializationConstraint` is one problem. 
The problem here seems to be because it wait for an `UpdateModelAction` and this is no longer fired at the startup. Only a `SetModelAction` is fired. So I assume that we can change it that it waits for this Action.

The second problem goes a little bit deeper and was not really easy to catch. I assume this was caused by the refactoring of the DI architecture: https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/45
Imagine the following scenario:

1. No editor is opened (but you have some markers)
2. You now double click on a marker
3. Now the `gotoMarker` method on the glsp-editor is called, where of course need to be waited until the DI is setup and the client is ready to accept actions.
4. Here the DI will setup The IdeActionDispatcher by call it's constructor and inside this constructor the injector will be set to the client.
5. As soon as this injector is set the CompletableFuture is completed for the injector and e.g. also the waiting future inside the `gotoMarker` will be resumed.
6. So the future will be resumed and as this wants to dispatch an action, an ActionDispatcher instance is called from the injector.
7. But the initialize of the IdeActionDispatcher is not finished, as it is still at the point where the injector is set the editor.

So IMO, the `editor.setInjector` mustn't be called in the constructor but later in a separate method.

PR for my solution suggestion: https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/47

**Comment by tortmayr** [comment]
Hi @ivy-lli 
thanks for your input and your suggested fix. I will check it out asap. :+1:
