### ISSUE TITLE
Pull out common bundle from org.eclipse.glsp.server

### ISSUE THREAD

**Issue by eneufeld** [eclipse-glsp/glsp#459]
The org.eclipse.glsp.server bundle has some packages which only define interfaces and types.
When consuming them you get all the dependencies from the server itself which might not be necessary. This is especially true if you use the modelserver with glsp.
I suggest to pull out a common bundle which would contains all interfaces and types, I can look through the code and point out the packages I was using, if this is any help to you.

**Comment by planger** [comment]
Sounds like a good idea in general, however, I think we need to more clearly define the exact use case of reuse in other components (ie which interfaces and types exactly are needed).
You mention the use case in the model server... so I think we should discuss with the model server team what they need so that they can make a suggestion.

**Comment by planger** [comment]
This issue got stale and it doesn't seem critical.
