### ISSUE TITLE
Global ActionDispatcher Thread is started for each connection and will never be stopped

### ISSUE THREAD

**Issue by ivy-lli** [eclipse-glsp/glsp#571]
For each connection (over LSP or WebSocket) a global ActionDispatcher Thread is started in addition to the session. So There are two ActionDispatcher Threads for each connection and only the one on the session is stopped if the connection is closed.

I think, the global ActionDispatcher Thread is created over the `DefaultServerGsonConfigurator`.
```java
diagramModules.values().stream()
   .map(module -> serverInjector.createChildInjector(module).getInstance(ServerConfigurationContribution.class))
   .forEach(contribution -> {
       contribution.configure(actionRegistry);
       contribution.configure(graphGsonConfigurator);
    });
```

Also other classes are instantiated twice e.g the `ModelSourceWatcher`. The first time with a fall back client id and the second time with the correct one.

So I think all this classes are only used by the client session injector and don't needed to be started via the global server injector.

Screenshot:
Only one theia integration started (with some full page refreshes). Only every second thread is stopped.
![image](https://user-images.githubusercontent.com/42733123/156782211-b64fc1e0-a39d-4ff5-b916-204d9594a7a5.png)

**Comment by tortmayr** [comment]
@ivy-lli Good catch! Thank your for reporting that! 

> So I think all this classes are only used by the client session injector and don't needed to be started via the global server injector.

Technically you are right. However we cannot really control which classes are indirectly created by the injector when we retrieve the `ServerConfigurationContribution`. In this particular case the `DefaultServerConfigurationContribution` has the action & operation handlers injected. Some of the action handlers in term inject the  `ActionDispatcher` or the `ModelSourceLoader` (e.g. the `RequestModelActionHandler` injects both). That's why they are indirectly constructed when retrieving the `ServerConfigurationContribution`.

However, what we can do is ensuring that all resources are safely disposed once they are no longer needed (i.e. the initial configuration of the `DefaultServerGsonConfigurator` has been completed).

I have prepared a PR to implement this behavior (https://github.com/eclipse-glsp/glsp-server/pull/151).
Using the theia integration everything now works as expected. The `global` action dispatcher is correctly disposed after startup and after multiple refreshes we still have only one running `ActionDispatcher` thread:

![Screenshot from 2022-03-05 01-43-02](https://user-images.githubusercontent.com/2311075/156860027-b1970f3a-eb1f-48f2-9aab-886972979516.png)

**Comment by ivy-lli** [comment]
Yes I also thought that this is maybe not easy possible, to control what is initialized by the injector. So I think this is also a good fix.

Thanks for your work!

**Comment by ivy-cst** [comment]
Sorry but that sounds not like a real solution for me! We use mainly websocket and for every connection everything is constructed twice and even a Thread is created for nothing? I do not like that.

**Comment by tortmayr** [comment]
>We use mainly websocket and for every connection everything is constructed twice and even a Thread is created for nothing? I do not like that.

 I agree, this is less than ideal. Unfortunately, I currently don't see a way around the fact that we have to retrieve the information about available action & operation handlers from the configured diagram modules to properly configure GSON on server startup.
 
However, we could make some optimizations to reduce the overhead.
From the top of my head I can think of two solutions:
- `Mock unneeded bindings in the temporary session`: To avoid creating a new Thread that basically serves no purpose we could bind the `ActionDispatcher` (and other classes) to a mock implementation that basically does nothing. This way we could ensure that at least no unnecessary additional resources are created just to be disposed right after. The downside of this approach is that we don't know which additional bindings have been made by adopters in the diagram module so there still could be some classes that instanter unnecessarily.
- `Enforce by convention that all Action & OperationHandlers must have an empty constructor`: This would allow us to bypass Guice entirely for the initial server configuration. Instead we could construct the action & operation handlers provided by the diagram module with Reflection and configure the `GSONConfigurator` this way. This sounds like the preferred solution  to me as we only construct the classes that are absolutely needed.

In addition, we could also tweak the server connection handling of the Eclipse Integration. Instead of eagerly disposing the GLSP server once all open diagram editor have been closes we could keep the server alive for a certain interval (e.g. 5 minutes) and allow new diagram widgets (and websocket connections)  to connect to the already running server instead of having to initialize a new one.
