### ISSUE TITLE
Make Java and Node server diagram module API more consistent?

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#620]
In the node server, we currently have a `configure(...)` method in which consumers are expected to bind mandatory implementations regarding their source model. In Java this is a bit more explicit because users need to implement abstract methods that directly deliver the implementation class for specific services.

Couldn't we just do the same in node?

**Comment by planger** [comment]
@tortmayr I sketched this appraoch in https://github.com/eclipse-glsp/glsp-server-node/pull/13. WDYT?

**Comment by tortmayr** [comment]
I'm in favor of having explicit methods for mandatory bindings, however I don't think we can just reuse the approach of the Java Server 1 to 1.

In the Java Server we use Guice as DI framework. Guice is fully class based so here it is fine to use dedicated methods
that just return a subclass of the service identifier class e.g.
```java
   @Override
   protected void configureBase() {
       bind(SourceModelStorage.class).to(bindSourceModelStorage());
       ...
   }

   protected abstract Class<? extends SourceModelStorage> bindSourceModelStorage();
}
```

However, in the node server we use inversify which is more flexible and allows other binding  variants 
in addition to class based bindings (constant value, toService, dynamic value ...).

The `BindingToSyntax` interface lists all the potential options:
```ts
interface BindingToSyntax<T> {
        to(constructor: new (...args: any[]) => T): BindingInWhenOnSyntax<T>;
        toSelf(): BindingInWhenOnSyntax<T>;
        toConstantValue(value: T): BindingWhenOnSyntax<T>;
        toDynamicValue(func: (context: Context) => T): BindingInWhenOnSyntax<T>;
        toConstructor<T2>(constructor: Newable<T2>): BindingWhenOnSyntax<T>;
        toFactory<T2>(factory: FactoryCreator<T2>): BindingWhenOnSyntax<T>;
        toFunction(func: T): BindingWhenOnSyntax<T>;
        toAutoFactory<T2>(serviceIdentifier: ServiceIdentifier<T2>): BindingWhenOnSyntax<T>;
        toProvider<T2>(provider: ProviderCreator<T2>): BindingWhenOnSyntax<T>;
        toService(service: ServiceIdentifier<T>): void;
    }
```
We can ignore factory and provider bindings but I think we should define the abstract methods in a way that
also enables the adopter to bind a service identifer `toConstantValue`,`toDynamicValue` and `toService`
   
Currently this is not possible.
Let's for example assume that the adopter wants to bind the `ModelSourceStorage` to a constant value.
With your proposal it would be required to bind a mock implementation for the `bindSourceModelStorage()` method
and than override the configure method to rebind the previously bound Mock to a constant value.
```ts
 override bindSourceModelStorage(): interfaces.Newable<SourceModelStorage> {
        return  {
              loadSourceModel: () => Promise.resolve(),
              saveSourceModel: () => {}
         };
    }

 override  protected configure(bind: interfaces.Bind, unbind: interfaces.Unbind, isBound: interfaces.IsBound, rebind: interfaces.Rebind): void {
   super.configure(bind,unbind,isBound,rebind);
   rebind(SourceModelStorage).toConstantValue(new MyConstantSourceModelStorage());
  }
```

Maybe the dedicated binding method could return a `BindingTarget` instead of `interfaces.Newable` 

```ts
  abstract bindSourceModelStorage(): BindingTarget<SourceModelStorage>;
```

And the `BindingTarget` type could look something like this:

```ts
 export type BindingTarget<T>= interfaces.Newable<T>| (context:interfaces.Context) => T | {constantValue: T} | {service: interfaces.ServiceIdentifer<T>
```
Then we could derive the corresponding to binding based on the actual value of the `BindingTarget`.
If the target  is a `Newable<T> =>  bind with `to`
If the target is a function =>  bind with `toDynamicValue`
if the target is an object with `constantValue` property => bind `toConstantValue`
if the target is an object with `service` property => bind `toService`

I'd have to do some testing if this actually works as expected. If it does I think we could
also use dedicated binding methods for all optional services.

**Comment by tortmayr** [comment]
Once we decided on strategy we should also apply the same strategy for the `TheiaIntegration` base module which currently uses a weird mixture between the `Guice way` and the `inversify way` bind providing explicit binding methods with void return type.

**Comment by planger** [comment]
Yeah, that's true, we somehow limit the power of inversify by following strictly just what I sketched.
If your approach with the `BindingTarget` type works, that'd be even better of course.

**Comment by tortmayr** [comment]
Another issue that we maybe should consider is the configurability of binding scopes.
In neither the Java nor the Node GLSP server it is currently possible to change the default scope.
e.g. the `SourceModelLoader` is always bound in Singleton scope and the adopter has no easy way to modify this
Admittedly this can be considered a corner case, nevertheless if we find a non invasive approach to enable configurability we 
should do it.
Maybe we could declare the service identifiers that should be bound in singleton in a Map? Than the adopter can just remove
a identifier from this map if he doesn't want/need singleton scope for it,

**Comment by planger** [comment]
Hm, yeah sure, if it is non-invasive that's fine. But I think we also should be careful to avoid over-generalizing here. For such corner-cases, I guess it is also ok, if consumers have to subclass a class higher in the class hierarchy of the diagram module and do everything themselves or rebind later on to their preferences.
