### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#638]
A user reported that building [java-emf-theia](https://github.com/eclipse-glsp/glsp-examples/tree/master/project-templates/java-emf-theia) seems to cause the following error:

```
Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check (default) on project org.eclipse.glsp.example.minimal: Failed during checkstyle execution: Failed during checkstyle configuration: unable to parse configuration stream: Unknown host [checkstyle.org](http://checkstyle.org/)
```

With the `-Dcheckstyle.skip` option, all worked fine for the user.

Can we please double-check? Thanks!

**Comment by ndoschek** [comment]
This issue with the checkstyle step seems to appear if the user is offline while executing the build (could verify that locally).
I doublechecked, and the checkstyle step passes on my local setup as well as on the CI consistently without errors.

Also I noticed, the error message states `... on project org.eclipse.glsp.example.minimal` instead of `jave-emf-theia`. @planger  Do you have additional information on that? Thanks1

**Comment by FlorentPastorSTM** [comment]
Hi @ndoschek,

I am the user reporting the issue.
Thanks for your investigations and your help. Then I guess it is a problem with my proxy...
I will investigate and I'll let you know.
