### ISSUE TITLE
Publish sources of `org.eclipse.glsp.server.emf`

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#742]
We seem to miss publishing the sources ("source feature") via p2 for [`org.eclipse.glsp.server.emf`](https://github.com/eclipse-glsp/glsp-server/tree/master/plugins/org.eclipse.glsp.server.emf). When I use

**Comment by xai** [comment]
This seems to have already been fixed by @ndoschek in eclipse-glsp/glsp-server#176 :-)
I verified that the `org.eclipse.glsp.server.emf` sources are included in `releng/org.eclipse.glsp.repository/target/org.eclipse.glsp.repository-1.1.0-SNAPSHOT.zip` after running `mvn clean verify`: ![Screenshot from 2022-09-22 18-02-30](https://user-images.githubusercontent.com/1155551/191796505-e9a56bf0-c476-4e4a-9f1c-d4206a7fa0bb.png)

**Comment by planger** [comment]
Oh, excellent, sorry for not checking the snapshots before opening this bug.
