### ISSUE TITLE
Diagram becomes dirty even though we have not done changes

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#766]
### Discussed in https://github.com/eclipse-glsp/glsp/discussions/765

<div type='discussions-op-text'>

<sup>Originally posted by **sathya-1994** October 13, 2022</sup>
I am using GLSP's vscode extension.

Steps to reproduce:
1. Open diagram form .wf file
2.  Try to edit node label using double
3.  Don't update label click on other node

Expected: Diagram editor should not be come dirty
Actual: Diagram editor will be dirty even though we have not changed content
</div>

**Comment by martin-fleck-at** [comment]
There was actually a bug in Sprotty about this. Sprotty always sent an action even if the content was the same. Since the action ends up as an operation command in our command stack, the editor will become dirty. On the server API there is currently no way to mark a handled operation as 'not performing any change' so even if the operation does nothing the command stack will be changed.
