### ISSUE TITLE
[Website-Docu] Don't mix docu for release version and nightly version

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#793]
Currently there is no versioning in the GLSP website documentation. If something changes after a new release and the contributor updates the corresponding docu section its no longer in sync i.e. adopters that use the release version can no longer use all the snippets without issues. Also it is not clear which parts of the documentation are referring to the release version and which are referring to the nightly version. 

I'd propose that we introduce versioning for the documentation. At the bare minimum we should separate release doc from documentation for upcoming changes.

**Comment by planger** [comment]
We've decided that whenever we update the documentation with content concerning aspects that aren't yet released, we'll apply those documentation updates to a branch with the name of the upcoming release instead of directly publishing it. Thus, the published documentation will always be in line with the latest release, and whenever there is a new release, we merge the documentation branch and publish it.
